### ISSUE TITLE
Crash during computation of distance from the center of the commune

### ISSUE THREAD

**Issue by VakankGrang** [orbisgis/MApUCE_tools#25]
During the execution of the "complete geoprocessing chain" for the urban area of Thionville
for the commune 57724 (Number 1 on 15) 
and the part "Compute the distance for the center of the commune"
I obtained the following crash

org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON DATA_WORK.USR_TO_CENTER(PK_USR)"; SQL statement:
CREATE TABLE DATA_WORK.USR_TO_CENTER (PK_USR integer primary key, DIST_TO_CENTER double precision) AS SELECT a.PK as PK_USR, ST_DISTANCE(ST_CENTROID(a.THE_GEOM), ST_CENTROID(b.THE_GEOM)) AS DIST_TO_CENTER FROM USR_MAPUCE a, COMMUNE_MAPUCE b [23505-192]

Thanks for your help

**Comment by ebocher** [comment]
same as #26

**Comment by ebocher** [comment]
Bug on

Start processing for area : 68224 -> Number 3 on 21
Importing the USR
Importing the buildings
Importing the roads
Importing the geometry of the spatial unit
Compute area volume
Compute form factor
Compute concavity
Compute contiguity
Compute compacity
Compute compactness
Compute main direction
Compute passive volume ratio
Compute fractal dimension
Compute the distance between buildings
org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Chunk 13931 no longer exists [1.4.192/9]"; SQL statement:
CREATE TABLE DATA_WORK.DIST (PK integer PRIMARY KEY, MIN_DIST double precision,  MEAN_DIST double precision, MAX_DIST double precision, STD_DIST double precision, PK_USR integer)AS SELECT a.PK, MIN(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MIN_DIST, AVG(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MEAN_DIST, MAX(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MAX_DIST, STDDEV_POP(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS STD_DIST,a.PK_USR FROM BUILDINGS_MAPUCE a, BUILDINGS_MAPUCE b WHERE a.PK<>b.PK AND a.PK_USR=b.PK_USR GROUP BY a.PK_USR, a.PK [50000-192]

**Comment by VakankGrang** [comment]
Hello,

Try with "mv_store=FALSE" option in the "database customisation" rider that appears when opening OrbisGIS. 

Best regards,
Robert

**Comment by ebocher** [comment]
Hello,
I will investigate a bit more on it.

**Comment by ebocher** [comment]
Issue on https://github.com/h2database/h2database/issues/373

**Comment by ebocher** [comment]
Fixed also with last H2 database release 1.4.193
