### ISSUE TITLE
Aggregation of building-type and building use

### ISSUE THREAD

**Issue by VakankGrang** [orbisgis/MApUCE_tools#27]
The MAPUCE geoprocessing chain aggregates the USR-, Block- and Building-Indicators
for one given agglomeration. However, in order to have a complete information on the urban
tissue additional data needs to be aggregated from the data at commune level.
- The building type (at building scale) (fields "BUILDING_TYPO" or "TYPO_RESULT")
- The entries THEME, PAI_BDTOPO and PAI_NATURE from the field "BUILDINGS_MAPUCE")

Eventually we could convert the information on the THEME and PAI into integers via a look-up
table (this would probably save a lot of space). However, there are many possible entries for the PAIs, so this could take some time.

Best regards,
Robert

**Comment by ebocher** [comment]
I will just clone the values (THEME, PAI_BDTOPO and PAI_NATURE) in the building_indicators table. 
Note there is no informations about THEME, PAI_BDTOPO and PAI_NATURE at other scales.
