### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by VakankGrang** [orbisgis/MApUCE_tools#51]
Hi,

You might you a look at the division-by-zero-crash I encountered 
during the treatment of the commune Béthune.

Start processing for area : 62770 -> Number 90 on 103
org.h2.jdbc.JdbcSQLException: Division by zero: "0.0"; SQL statement:
CREATE TABLE DATA_WORK.USR_DENS_AREA_HYDRO 
(PK_USR integer primary key, HYDRO_DENS double precision) 
AS SELECT PK as PK_USR, ROUND(HYDRO_SURFACE/USR_AREA,4) 
as HYDRO_DENS FROM USR_MAPUCE [22012-193]

Best regards,
Robert

**Comment by ebocher** [comment]
Thanks I will add a workaround

**Comment by ebocher** [comment]
I propose to filter a USR with a zero area

**Comment by gpetit** [comment]
+1 if the USR has an area equal to 0, it make no sense to keep this object

**Comment by ebocher** [comment]
Fix on the database with
delete from lienss.usr where st_area(the_geom)=0;
