### ISSUE TITLE
OrbisGis stalls during the computation of the distance between buildings

### ISSUE THREAD

**Issue by VakankGrang** [orbisgis/MApUCE_tools#52]
Hi,

During the treatment of the urban area "Brest", for the commune 29189
the complete geoprocessing chain stalls at the step "compute the distance between buildings".
I killed OrbisGis after ~ 1 hour, it was still using a full CPU. 
Normally this step takes less than 1 minute on my machine.

You might have a look at this problem.

Best regards,
Robert

**Comment by ebocher** [comment]
Have a look on the commune 29189, there is only one USR ;-) and we are computing all distance between buildings. Sorry but it's a bug on the input data.
