### ISSUE TITLE
Crash for Perpignan

### ISSUE THREAD

**Issue by VakankGrang** [orbisgis/MApUCE_tools#53]
During the calculation of the indicators for Perpignan, the following error occurred:
Start processing for area : 66136 -> Number 5 on 15
...
Finalize the USR indicators table
org.h2.jdbc.JdbcSQLException: Exception calling user-defined function: "intersection(POLYGON ((689233.0971363089 6177680.445158442, 689255.2201911771 6177684.147451778, 689255.220191177 6177684.147451778, 689255.2202058757 6177684.147453134, 689269.1999981931 6177684.400099984, 689269.2000052559 6177684.400099862, 689284.3999932453 6177683.600100494, 689304.4999812945 6177687.400098235, 689324.8999793155 6177691.300097857, 689343.8999774392 6177695.700097422, 689343.8999787754 6177695.700097722, 689365.9999787754 6177700.500097722, 689365.9999830874 6177700.500098559, 689399.7999830875 6177706.300098559, 689399.7999923833 6177706.300099709, 689428.5999906138 6177708.500099574, 689447.2999888402 6177710.600099375, 689447.2999889569 6177710.600099388, 689456.2999889569 6177711.600099388, 689456.2999977535 6177711.600099974, 689465.1999965044 6177711.800099947, 689484.1999890711 6177712.700099595, 689497.4999829597 6177715.000098538, 689497.4999895635 6177715.000099454, 689513.6999895634 6177716.700099454, 689513.6999962988 6177716.700099932, 689527.1999885817 6177717.200099646, 689534.1500108169 6177718.54526524, 689534.1500302026 6177718.54526706, 689534.1500495737 6177718.545265091, 689534.150068196 6177718.545259404, 689534.1500853632 6177718.545250217, 689534.1501004247 6177718.545237877, 689534.1501128093 6177718.545222852, 689534.1501220476 6177718.545205712, 689534.1501277894 6177718.545187107, 689543.9600979702 6177670.600020045, 689543.9600999759 6177670.60000219, 689543.9600987543 6177670.599984265, 689543.9600943447 6177670.599966847, 689533.5200943447 6177640.889966847, 689533.5200871803 6177640.889951014, 689526.0300871803 6177627.559951014, 689526.0300748734 6177627.559933713, 689526.0300591909 6177627.559919399, 689526.0300408403 6177627.55990872, 689526.0300206485 6177627.559902155, 689502.1000206484 6177622.509902155, 689502.1000005781 6177622.509900002, 689502.0999804842 6177622.509901922, 689502.0999611854 6177622.50990784, 689497.4699857425 6177624.459897498, 689489.4900315065 6177623.479903118, 689476.0300485257 6177616.009912563, 689476.0300288356 6177616.009904248, 689476.0300078284 6177616.009900306, 689476.0299864634 6177616.00990092, 689467.3200071342 6177617.199898097, 689397.9700452557 6177597.5899088755, 689392.350060227 6177593.34992017, 689392.3500458607 6177593.349911136, 689392.3500301738 6177593.34990466, 689392.3500136177 6177593.349900931, 689374.890021076 6177590.949901957, 689277.7100282962 6177562.279904087, 689277.7100264818 6177562.27990357, 689166.9400324146 6177531.859905199, 689159.4900508769 6177528.789912807, 689151.4900617474 6177522.50992134, 689151.4900617471 6177522.50992134, 689151.4900430769 6177522.509909754, 689151.4900223268 6177522.509902524, 689151.4900004986 6177522.509900001, 689151.4899786463 6177522.509902306, 689144.1699960029 6177524.109898512, 689136.1600213692 6177523.009901996, 689101.4400288713 6177512.539904258, 689101.4400288712 6177512.539904258, 689101.4400100097 6177512.539900502, 689101.439990778 6177512.539900426, 689092.9100079974 6177513.329898831, 689051.8500247529 6177502.839903112, 689051.8500095134 6177502.839900454, 689051.8499940464 6177502.839900177, 689024.5199940464 6177504.469900177, 689024.5199791569 6177504.469902196, 689024.519964738 6177504.469906423, 689002.599964738 6177512.729906424, 689002.5999462286 6177512.729915688, 689002.5999300228 6177512.729928563, 689002.5999168151 6177512.7299445, 689002.599907171 6177512.729962815, 688995.749907171 6177529.829962814, 688995.7499021286 6177529.829979477, 688989.2599043566 6177560.779968853, 688958.0299088123 6177630.159958954, 688958.0299020017 6177630.159980092, 688958.0299000245 6177630.160002212, 688958.0299029781 6177630.160024223, 688964.85086053 6177657.4804442795, 688964.8508679145 6177657.480464387, 688964.8508794117 6177657.480482459, 688964.8508944941 6177657.480497669, 688964.8509124697 6177657.480509318, 688964.8509325137 6177657.480516871, 688977.2999749618 6177660.700096815, 688977.2999789573 6177660.700097761, 688999.5999786726 6177665.500097699, 689016.7999784272 6177669.300097645, 689016.7999821539 6177669.300098395, 689037.1999821538 6177673.000098395, 689037.1999871139 6177673.000099166, 689054.899987114 6177675.300099166, 689054.8999878459 6177675.300099258, 689089.1999878458 6177679.5000992585, 689089.2000087919 6177679.500099612, 689089.2000293521 6177679.500095596, 689089.2000486241 6177679.500087382, 689101.6000486241 6177672.600087382, 689101.6000548841 6177672.600083592, 689111.5000451882 6177666.100089958, 689117.8000169664 6177663.800100261, 689131.2999934889 6177664.000099914, 689143.3999839792 6177665.400098815, 689160.5999795137 6177669.000097879, 689160.5999977659 6177669.000099975, 689178.4999960222 6177669.400099936, 689197.6999888865 6177670.500099527, 689215.0999731218 6177673.4000969, 689232.8372969453 6177680.401672093, 689232.8372969454 6177680.401672093, 689232.8373171565 6177680.401677705, 689233.0971363084 6177680.445158442, 689233.0971363083 6177680.445158442, 689233.0971363089 6177680.445158442)), POLYGON ((685776.9999157478 6176799.999946134, 685776.9999157477 6176799.999946134, 685776.9999070356 6176799.999963154, 685776.9999017222 6176799.999981521, 685776.9999000016 6176800.000000563, 685776.9999019366 6176800.000019586, 685776.9999074567 6176800.000037891, 685776.99991636 6176800.000054812, 685776.9999283209 6176800.000069729, 685776.9999429022 6176800.000082096, 685776.9999595709 6176800.000091463, 685776.9999777176 6176800.000097486, 685776.9999777175 6176800.000097486, 685811.9999777175 6176808.000097486, 685811.9999777176 6176808.000097486, 685811.9999914599 6176808.000099635, 685846.9999914599 6176811.000099635, 685847.0000090536 6176811.000099589, 685912.9999992857 6176805.000100477, 685931.9999873183 6176807.0000992175, 686144.9999614081 6176839.000095325, 686151.9999375462 6176844.00007828, 686160.9999205485 6176852.000063172, 686208.9999086994 6176940.0000414485, 686215.9999061656 6176959.000034571, 686215.9999061658 6176959.000034571, 686215.9999128424 6176959.000049026, 686224.9999128424 6176975.000049026, 686224.9999128423 6176975.000049026, 686224.9999292893 6176975.000070711, 686227.9999292893 6176978.000070711, 686227.9999359816 6176978.000076822, 686239.9999347616 6176988.000075805, 686266.9999335636 6177012.0000747405, 686266.9999335634 6177012.0000747405, 686266.9999436039 6177012.00008258, 686307.9999392504 6177040.000079608, 686327.9999296095 6177057.000071413, 686348.9999191216 6177081.000059427, 686370.9999133096 6177117.000049916, 686396.9999120708 6177165.000047629, 686396.9999125843 6177165.000048565, 686401.9999125843 6177174.000048565, 686401.9999125844 6177174.000048565, 686401.9999236176 6177174.0000645425, 686401.9999375305 6177174.000078087, 686411.9999375305 6177182.000078087, 686411.9999375304 6177182.000078087, 686411.9999539339 6177182.000088758, 686411.9999721013 6177182.00009603, 686411.9999913371 6177182.0000996245, 686434.9999858238 6177184.000099145, 686479.9999719709 6177193.000096374, 686523.99996396 6177210.000093279, 686523.9999639599 6177210.000093279, 686523.9999844037 6177210.000098776, 686542.9999844037 6177213.000098776, 686543.0000020395 6177213.000099979, 686543.0000196116 6177213.000098058, 686573.0000196116 6177207.000098058, 686573.0000245938 6177207.000096928, 686640.0000214224 6177190.000097733, 686666.9999944287 6177185.000102731, 686676.9999433602 6177188.000087411, 686695.9999228766 6177210.000063693, 686710.9999215117 6177229.000061965, 686710.9999215119 6177229.000061965, 686710.9999339669 6177229.000075097, 686710.9999485852 6177229.00008577, 686710.9999648876 6177229.000093633, 686726.9999648876 6177235.000093633, 686726.9999648877 6177235.000093633, 686726.9999809294 6177235.000098165, 686726.999997501 6177235.000099969, 686727.0000141421 6177235.000098995, 686755.0000093266 6177231.000099683, 686822.0000044731 6177228.0000999, 686822.0000086629 6177228.0000996245, 686845.0000086629 6177226.0000996245, 686845.0000150442 6177226.000098862, 686891.0000013453 6177219.000100946, 686946.9999849274 6177226.000098894, 687046.9999716999 6177244.000096513, 687075.9999589061 6177256.000091219, 687118.9999561164 6177277.000089857, 687118.9999612768 6177277.000092198, 687168.9999612768 6177298.000092198, 687168.9999644004 6177298.000093449, 687189.9999644004 6177306.000093449, 687189.9999674009 6177306.000094538, 687218.9999674009 6177316.000094538, 687218.9999762547 6177316.00009714, 687263.9999749528 6177327.000096821, 687285.9999736883 6177333.000096477, 687285.9999757464 6177333.000097014, 687377.999963341 6177356.000093913, 687399.9999463774 6177368.00008466, 687458.9999411014 6177411.000080815, 687458.9999411015 6177411.000080815, 687458.9999503861 6177411.000086824, 687465.9999449829 6177415.000083737, 687521.99994 6177457.00008, 687521.9999399999 6177457.00008, 687521.9999522486 6177457.000087863, 687567.9999522486 6177482.000087863, 687567.9999522488 6177482.000087863, 687567.9999631785 6177482.000092974, 687668.9999604359 6177522.000091888, 687756.9999068187 6177563.000066907, 687758.9999006116 6177581.000011043, 687758.999901613 6177581.000017889, 687760.999901613 6177592.000017889, 687760.9999016131 6177592.000017889, 687760.9999069272 6177592.000036571, 687760.9999157529 6177592.000053874, 687760.9999277571 6177592.000069144, 687760.9999424868 6177592.000081806, 687760.9999593862 6177592.000091381, 687769.9999593862 6177596.000091381, 687769.9999593863 6177596.000091381, 687769.9999794989 6177596.000097876, 687917.999975069 6177627.000096949, 687966.9999699385 6177642.000095378, 688000.9999692179 6177653.000095145, 688000.999969218 6177653.000095145, 688000.9999835601 6177653.000098639, 688030.9999835601 6177658.000098639, 688030.9999881787 6177658.000099299, 688072.9999835037 6177663.000098742, 688123.9999761852 6177674.000097163, 688203.9999734843 6177696.000096421, 688203.9999734844 6177696.000096421, 688203.999986209 6177696.000099044, 688282.999985443 6177707.000098937, 688366.9999847059 6177720.000098824, 688366.9999957182 6177720.000099909, 688436.9999957182 6177723.000099909, 688437.0000073871 6177723.000099727, 688464.0000073871 6177721.000099727, 688464.0000249196 6177721.000096845, 688464.0000416655 6177721.000090906, 688488.0000416655 6177710.000090906, 688488.00005547 6177710.000083205, 688539.0000526062 6177676.0000851145, 688560.0000349873 6177664.000095182, 688576.0000010261 6177661.0001015505, 688599.9999725801 6177665.000096809, 688626.9999622703 6177676.000092609, 688626.9999622701 6177676.000092609, 688626.9999858579 6177676.000098995, 688640.9999847154 6177678.000098832, 688652.9999835601 6177680.000098639, 688652.9999964308 6177680.0000999365, 688680.9999964308 6177681.0000999365, 688681.0000074262 6177681.000099724, 688775.0000026692 6177674.000100078, 688917.9999979025 6177677.000099978, 689007.9999977783 6177679.000099976, 689008 6177679.0001, 689032.9999876897 6177679.0001, 689088.9999757464 6177693.000097014, 689088.9999963389 6177693.000099933, 689089.0000170899 6177693.000098529, 689089.0000371016 6177693.000092863, 689089.0000555083 6177693.000083179, 689089.0000715139 6177693.000069899, 689089.0000844261 6177693.000053593, 689089.0000936862 6177693.00003497, 689089.0000988937 6177693.000014834, 689098.0000988937 6177633.000014834, 689098.0001 6177633, 689098.0001 6177631.000014996, 689125.0000956013 6177543.000029332, 689125.0000964764 6177543.000026312, 689128.0000964764 6177532.000026312, 689128.0000997327 6177532.000007307, 689128.0000992812 6177531.999988032, 689128.0000951388 6177531.9999692, 689128.0000874593 6177531.999951514, 689128.0000765285 6177531.999935631, 689128.0000627525 6177531.9999221405, 689128.0000466437 6177531.999911545, 689128.0000288008 6177531.999904237, 688995.0000288008 6177491.999904237, 688995.0000274722 6177491.999903847, 688946.0000295567 6177477.999904443, 688937.0000316228 6177474.999905132, 688937.0000274722 6177474.999903847, 688916.0000323852 6177468.999905251, 688911.000037139 6177466.999907153, 688911.0000287348 6177466.999904217, 688891.0000287348 6177460.999904217, 688891.0000274722 6177460.999903847, 688870.0000276465 6177454.999903897, 688832.0000278058 6177443.999903943, 688832.0000274722 6177443.999903847, 688825.0000274722 6177441.999903847, 688825.000026963 6177441.999903704, 688800.0000311038 6177434.999904864, 688792.0000351124 6177431.999906367, 688792.0000351123 6177431.999906367, 688792.0000242536 6177431.999902986, 688784.0000242536 6177429.999902986, 688784.0000196116 6177429.999901942, 688779.0000257164 6177428.999903163, 688776.0000316228 6177427.999905132, 688776.0000287348 6177427.999904217, 688766.0000287348 6177424.999904217, 688766.0000274722 6177424.999903847, 688759.0000274722 6177422.999903847, 688759.0000231621 6177422.99990272, 688738.0000231621 6177417.99990272, 688738.0000196116 6177417.999901942, 688733.0000257164 6177416.999903163, 688727.000090869 6177414.99992488, 688725.0000991228 6177399.999986784, 688725.0000989533 6177399.999985569, 688718.0000990678 6177351.999986354, 688711.0000991703 6177297.999987145, 688687.0000992832 6177113.999988009, 688684.0000993884 6177086.999988957, 688684.0000970142 6177086.9999757465, 688683.0000990443 6177082.999983867, 688673.0000996962 6176954.999992211, 688673.000099624 6176954.999991337, 688667.0000997907 6176885.9999932535, 688657.0001000859 6176678.999999363, 688665.0000999258 6176454.000003864, 688667.0000999133 6176406.000004163, 688667.0001 6176406, 688667.0001 6176401.000001724, 688669.0000999308 6176343.000003729, 688673.0000999201 6176243.000003997, 688673.0000986488 6176242.999983617, 688673.0000932643 6176242.99996392, 688673.0000839907 6176242.999945727, 688673.0000712151 6176242.999929797, 688673.00005547 6176242.999916795, 688670.0000609178 6176240.999920427, 688638.0000812337 6176212.999938203, 688612.0000922354 6176158.999961053, 688593.0000944188 6176106.999967028, 688581.0000948684 6176070.999968377, 688581.0000948682 6176070.999968377, 688581.0000845488 6176070.999946601, 688569.0000845488 6176051.999946601, 688569.000084549 6176051.999946601, 688569.0000738956 6176051.999932624, 688538.0000738956 6176017.999932624, 688538.0000738954 6176017.999932624, 688538.0000612416 6176017.999920947, 688538.0000467718 6176017.999911612, 688538.0000309153 6176017.999904899, 688538.0000141421 6176017.999901005, 688503.0000141421 6176012.999901005, 688503 6176012.9999, 688485.0000045358 6176012.9999, 688463.0000318356 6176010.999902482, 688438.0000725165 6175995.99992689, 688427.0000853282 6175977.999947855, 688427.0000853284 6175977.999947855, 688427.0000707107 6175977.999929289, 688423.0000896122 6175973.9999481905, 688416.0000965616 6175947.999974003, 688416.0000965617 6175947.999974003, 688416.0000885831 6175947.9999536, 688405.0000885831 6175926.9999536, 688405.0000885833 6175926.9999536, 688405.0000764912 6175926.999935586, 688389.0000764912 6175907.999935586, 688389.0000749838 6175907.999933838, 688374.0000781002 6175890.9999373695, 688366.0000973309 6175879.9999638125, 688364.0001 6175855.999995841, 688364.0001 6175852.000006226, 688370.0000992278 6175804.000012403, 688370.0000992278 6175803.999987597, 688368.0000992278 6175787.999987597, 688368.0000924678 6175787.999961925, 688361.0000924678 6175770.999961925, 688361.0000837244 6175770.999945317, 688361.0000720317 6175770.999930635, 688361.0000578017 6175770.9999183975, 688337.0000578017 6175753.9999183975, 688337.0000432531 6175753.999909838, 688337.0000274722 6175753.999903847, 688295.0000274722 6175741.999903847, 688295.0000105668 6175741.99990056, 688294.9999933481 6175741.999900222, 688279.9999933481 6175742.999900222, 688279.9999792496 6175742.999902177, 688247.0000175262 6175749.999894057, 688205.0000584568 6175724.999918421, 688164.0000649262 6175689.999923944, 688164.0000413803 6175689.999908963, 688131.0000413803 6175674.999908963, 688131.0000200323 6175674.999902027, 688130.9999976751 6175674.999900027, 688087.9999976751 6175675.999900027, 688087.9999832585 6175675.999901411, 688034.9999931228 6175684.999899736, 687971.0000138441 6175682.999900384, 687939.0000499683 6175674.999909415, 687916.0000796188 6175652.999937776, 687912.0000868243 6175645.999950386, 687912.0000860292 6175645.999949019, 687896.0000860292 6175618.999949019, 687896.0000860291 6175618.999949019, 687896.0000790415 6175618.999938743, 687865.0000790415 6175578.999938743, 687865.0000783497 6175578.99993786, 687842.0000783497 6175549.99993786, 687842.0000783496 6175549.99993786, 687842.0000639556 6175549.999923126, 687842.0000468477 6175549.999911653, 687842.0000277521 6175549.9999039285, 687842.000007479 6175549.9999002805, 687762.000007479 6175543.9999002805, 687762.0000059892 6175543.99990018, 687612.0000245005 6175534.999901291, 687568.0000472824 6175514.999911646, 687531.0000527934 6175491.999915072, 687531.0000527935 6175491.999915072, 687531.0000369584 6175491.99990708, 687531.0000199605 6175491.999902013, 687477.0000199605 6175480.999902013, 687477.0000199606 6175480.999902013, 687477.0000057874 6175480.999900168, 687408.0000227657 6175476.999901152, 687348.0000388639 6175451.99990786, 687292.0000433082 6175427.999909764, 687247.0000633477 6175403.999920452, 687227.0000767186 6175380.999935828, 687190.0000779213 6175334.999937324, 687190.0000779212 6175334.999937324, 687190.0000622746 6175334.999921758, 687141.0000622746 6175295.999921758, 687141.0000475149 6175295.99991201, 687091.0000475149 6175268.99991201, 687091.0000231621 6175268.99990272, 687007.0000252367 6175248.999903213, 686947.0000418134 6175231.99990791, 686927.0000544988 6175218.999916156, 686927.0000544989 6175218.999916156, 686927.0000384615 6175218.999907692, 686855.0000384615 6175188.999907692, 686855.0000384614 6175188.999907692, 686855.0000204522 6175188.999902113, 686855.0000017158 6175188.999900015, 686854.9999829186 6175188.99990147, 686854.9999647286 6175188.999906427, 686854.9999477923 6175188.99991471, 686854.9999327117 6175188.999926025, 686854.9999200228 6175188.99993997, 686854.9999101768 6175188.999956048, 686854.9999035236 6175188.999973688, 686851.9999035236 6175199.999973688, 686851.9999000593 6175199.999996558, 686851.999901942 6175200.000019612, 686853.999901942 6175210.000019612, 686853.9999076388 6175210.000038333, 686853.9999168725 6175210.000055586, 686853.9999292893 6175210.000070711, 686858.9999292893 6175215.000070711, 686858.9999359816 6175215.000076822, 686864.9999359816 6175220.000076822, 686864.9999375305 6175220.000078087, 686879.9999305937 6175232.000072537, 686886.9999106952 6175240.000049796, 686890.9999029341 6175253.000024572, 686892.999901942 6175263.000019612, 686892.9999076923 6175263.000038462, 686897.9999076923 6175275.000038462, 686897.9999080276 6175275.000039256, 686932.9999080276 6175357.000039256, 686932.9999088078 6175357.000041037, 686941.999906108 6175377.000035037, 686944.9998994115 6175387.000012715, 686943.9999002838 6175411.9999909075, 686940.9999057191 6175432.999952859, 686939.9999292893 6175433.999929289, 686939.999916853 6175433.999944443, 686939.9999076121 6175433.999961732, 686939.9999019215 6175433.999980491, 686939.9999 6175434, 686939.9999 6175442, 686939.9999016047 6175442.000017842, 686939.999906367 6175442.000035113, 686942.999906367 6175450.000035113, 686942.9999080854 6175450.000039392, 686945.9999080854 6175457.000039392, 686945.9999080856 6175457.000039392, 686945.9999173271 6175457.00005626, 686945.9999296269 6175457.000071047, 686945.99994453 6175457.000083205, 686951.999936292 6175461.000077713, 686958.9998855876 6175468.000027009, 686947.9999051316 6175500.999968377, 686947.9999044221 6175500.999970592, 686939.9999044221 6175526.999970592, 686939.999901942 6175526.999980388, 686936.9999041997 6175541.9999691, 686931.9999104672 6175552.999955311, 686925.9999201717 6175563.999937519, 686913.99993257 6175574.9999261545, 686902.9999327327 6175584.999926006, 686902.9999327324 6175584.999926006, 686902.9999222759 6175584.99993708, 686902.9999136222 6175584.999949613, 686895.9999136222 6175596.999949613, 686895.9999136223 6175596.999949613, 686895.9999033766 6175596.999974234, 686891.9999033766 6175611.999974234, 686891.9999018852 6175611.999980674, 686878.9999018852 6175677.999980674, 686878.9999014789 6175677.9999828655, 686874.9999014789 6175700.9999828655, 686874.9999006789 6175700.999988368, 686861.9999007306 6175811.999987926, 686846.999900785 6175930.999987494, 686846.9999004963 6175930.99999005, 686844.999900983 6175950.999985183, 686843.999901942 6175955.999980388, 686843.9999 6175955.999999916, 686843.9999019093 6175956.000019447, 686843.999907596 6175956.00003823, 686843.9999168414 6175956.000055539, 686843.9999292893 6175956.000070711, 686846.9999292893 6175959.000070711, 686846.999942077 6175959.000081517, 686846.9999564881 6175959.0000900375, 686846.999972119 6175959.000096034, 686877.999972119 6175968.000096034, 686877.9999721189 6175968.000096034, 686877.9999872028 6175968.0000991775, 686908.9999610754 6175972.000095806, 686912.9999 6175975.00005, 686912.9999 6175979, 686912.9999006116 6175979.000011043, 686919.9998916842 6176041.999930696, 686916.9999683772 6176042.999905132, 686916.9999676857 6176042.999905365, 686834.9999676857 6176070.999905365, 686834.9999676858 6176070.999905365, 686834.9999463124 6176070.999915634, 686812.9999463124 6176084.999915634, 686812.99994453 6176084.999916795, 686806.99994453 6176088.999916795, 686806.9999369407 6176088.999922388, 686790.999937194 6176101.999922182, 686785.9999425344 6176105.99991791, 686739.9999480053 6176133.99991458, 686739.9999330377 6176133.99992573, 686739.9999204025 6176133.999939467, 686739.9999105403 6176133.999955312, 686739.9999037943 6176133.999972715, 686739.9999003997 6176133.999991068, 686739.9999004747 6176134.000009732, 686739.9999040166 6176134.000028057, 686739.9999040165 6176134.000028057, 686758.9998750133 6176198.999928836, 686645.9999751418 6176227.999903139, 686645.999971061 6176227.999904279, 686602.999971061 6176240.999904279, 686602.9999596897 6176240.9999084845, 686518.9999596897 6176277.9999084845, 686518.9999448609 6176277.999916575, 686518.9999316059 6176277.999927047, 686502.9999398532 6176292.999919315, 686490.9999564823 6176299.999909614, 686459.9999706273 6176311.999904139, 686412.0000665246 6176322.999882163, 686388.0000949977 6176249.999968768, 686388.0000869484 6176249.999950604, 686388.000075467 6176249.999934389, 686388.0000610068 6176249.999920765, 686388.0000441384 6176249.999910268, 686388.0000255278 6176249.999903313, 686388.0000059095 6176249.999900174, 686387.999986058 6176249.999900977, 686387.9999667568 6176249.999905688, 686387.9999487677 6176249.999914121, 686387.999932801 6176249.999925944, 686333.9999349538 6176298.999923991, 686240.9999372248 6176373.999922159, 686240.9999372246 6176373.999922159, 686240.9999256526 6176373.999933124, 686240.9999159704 6176373.999945788, 686220.9999258436 6176404.999930484, 686193.9999404772 6176424.999919645, 686193.9999359816 6176424.999923178, 686187.9999375612 6176429.999921862, 686110.9999391785 6176488.999920622, 686110.9999385732 6176488.99992109, 685943.9999385732 6176618.99992109, 685943.9999336385 6176618.999925192, 685881.9999551692 6176673.999906093, 685869.9999835601 6176675.999901361, 685869.999966493 6176675.999905781, 685869.9999504675 6176675.999913129, 685869.9999359816 6176675.999923178, 685863.9999359816 6176680.999923178, 685863.9999359815 6176680.999923178, 685863.9999210648 6176680.999938606, 685856.9999210648 6176689.999938606, 685856.9999210646 6176689.999938606, 685856.9999138066 6176689.999949298, 685846.9999152309 6176706.999946876, 685844.9999222883 6176709.99993629, 685815.9999292893 6176738.999929289, 685815.9999157478 6176738.999946134, 685776.9999157478 6176799.999946134))): found non-noded intersection between LINESTRING ( 689232.8373171565 6177680.401677705, 689233.0971363084 6177680.445158442 ) and LINESTRING ( 689233.0971363083 6177680.445158442, 689233.0971363089 6177680.445158442 ) [ (689233.0971363084, 6177680.445158442, NaN) ]"; SQL statement:
update USR_INDICATORS AS a SET dcomiris =  (SELECT b.dcomiris FROM IRIS_MAPUCE b WHERE a.THE_GEOM && b.THE_GEOM ORDER BY ST_AREA(ST_INTERSECTION(st_buffer(a.THE_GEOM,0.0001), st_buffer(b.THE_GEOM, 0.0001))) DESC LIMIT 1); [90105-193]

Best regards,
Robert

**Comment by ebocher** [comment]
Oupps topology exception due to a bad IRIS geometry

**Comment by ebocher** [comment]
@VakankGrang  is this issue fixed ?
