### ISSUE TITLE
Unable to create typologies

### ISSUE THREAD

**Issue by gpetit** [orbisgis/MApUCE_tools#61]
I'm using the fresh snapshot release of OG (thanks to PPA).
I launched OG via ```orbisgis -clean```.
Then, I installed the MAPUCE_Tools plugin and I executed the "1-Import commune areas" script.
When I launch the "Complete Geoprocessing chain" on a specific city (here Bordeaux - 33063), I have the following error:

```
Download the MAPuCE model - mapuce-rf-2.2.RData - used to classify the buildings.
groovy.lang.MissingMethodException: No signature of method: org.renjin.script.RenjinScriptEngine.getScriptEngine() is applicable for argument types: () values: []

=====================================
WPS Process : Complete geoprocessing chain
=====================================
Result : FAILED
Log : 
00:00:00 : INFO : ACCEPTED
00:00:00 : INFO : IDLE
00:00:00 : ERROR : FAILED
```
Note that all tables are created ... but are empty

@SPalominos can you have a look quickly ? This plugin should be stabilized for a long time
@ebocher

**Comment by ebocher** [comment]
I will try to fix this regression

**Comment by ebocher** [comment]
Done

**Comment by gpetit** [comment]
Great. Thx @ebocher
